
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZlbmthdGVzaDEiLCJpYXQiOjE3MjEyOTA0Nzd9.V3dBXjeeiZtskOEb1j5UBxueC1n32AN88mZUFb1-tEM
###
POST http://localhost:3000/signup/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZlbmthdGVzaDEiLCJpYXQiOjE3MjEyOTA0Nzd9.V3dBXjeeiZtskOEb1j5UBxueC1n32AN88mZUFb1-tEM
Content-Type: application/json

{
    "username":"Venkatesh1",
    "password":"Rahul123"
}

###
POST http://localhost:3000/signin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZlbmthdGVzaDEiLCJpYXQiOjE3MjEyOTA0Nzd9.V3dBXjeeiZtskOEb1j5UBxueC1n32AN88mZUFb1-tEM
Content-Type: application/json

{
    "username":"Venkatesh1",
    "password":"Rahul123"
}

###

POST http://localhost:3000/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZlbmthdGVzaDEiLCJpYXQiOjE3MjEyOTA0Nzd9.V3dBXjeeiZtskOEb1j5UBxueC1n32AN88mZUFb1-tEM
Content-Type: application/json

{
    "id":6,
    "name":"Venkatesh",
    "date":"23/12/2023",
    "age":25,
    "username":"Venkatesh1"
}

###

GET http://localhost:3000/appointments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZlbmthdGVzaDEiLCJpYXQiOjE3MjEyOTA0Nzd9.V3dBXjeeiZtskOEb1j5UBxueC1n32AN88mZUFb1-tEM